[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.build]
cmds = [
  "cd frontend && yarn install && yarn build",
  "cd backend && yarn install"
]

[phases.start]
cmd = "cd backend && yarn start"
