[tools]
yarn = "1.22.19"

[phases.setup]
commands = [
  "cd frontend && yarn install && yarn build",  # build React app
  "cd backend && yarn install"                  # install backend dependencies
]

[phases.run]
cmd = "cd backend && yarn start"